Distribution Team
buildpacks/rfcs pull request #113
Opened 2020-09-03 15:55 UTC by jkutner

[Readable]()

2020-09-03 18:21 UTC, hone commented on text/0000-distribution-team.md
> +* [CircleCI Pack Orb](https://github.com/buildpacks/pack-orb)
Why the CircleCI orb and not the Tekton examples?

2020-09-04 20:20 UTC, hone commented on text/0000-distribution-team.md
> +
Can you also add the description/charter from the [community PR](https://github.com/buildpacks/community/pull/34/files):

> The Distribution team is responsible for maintaining tools and services that support the distribution, discovery, and integration of buildpacks.

2020-09-04 20:20 UTC, hone commented on text/0000-distribution-team.md
> +- Who are the maintainers?
Travis + Joe?

2020-09-08 08:35 UTC, dfreilich reviewed
In general, the idea is great. I'm not sure I love the name though - distribution sounds like it is in charge of distributing the Buildpacks products (either the lifecycle, or pack), but that seems to be more the responsibility of the platform team (as it focuses on controlling platforms on which you can run the lifecycle), and doesn't seem to accurately fit the core responsibility of the new team, which will focus more on the registration-yanking paths, and not really distributing buildpacks or the lifecycle.

2020-09-08 14:03 UTC, jromero commented
> In general, the idea is great. I'm not sure I love the name though - distribution sounds like it is in charge of distributing the Buildpacks products (either the lifecycle, or pack), but that seems to be more the responsibility of the platform team (as it focuses on controlling platforms on which you can run the lifecycle), and doesn't seem to accurately fit the core responsibility of the new team, which will focus more on the registration-yanking paths, and not really distributing buildpacks or the lifecycle.

The term distribution, like almost every other term, can have different meaning depending on context. In this context, we are talking about the project and thereby the spec (not the products). I think of it as similar terms to "OCI distribution spec". It centers around how buildpacks should be distributed. The term you seem to be describing I think of as delivery.

All that said, if there are alternative names that would further clear this potential confusion I think it's worth discussing.

2020-09-09 19:20 UTC, hone requested changes
I'd like to see a description of the team.

2020-09-15 20:14 UTC, sclevine approved these changes

2020-09-21 20:26 UTC, nebhale approved these changes

2020-09-23 13:25 UTC, jkutner commented
@hone description added in 58b8f72

2020-09-23 17:21 UTC, hone approved these changes

2020-09-23 19:12 UTC, ekcasey commented
Final Comment Period with merge disposition, closing on 30 September, 2020.

2020-10-08 15:03 UTC, merged